/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DefaultLayout: typeof import('./src/layouts/DefaultLayout.vue')['default']
    HomeProducts: typeof import('./src/components/home/HomeProducts.vue')['default']
    HomeServices: typeof import('./src/components/home/HomeServices.vue')['default']
    ProductCard: typeof import('./src/components/products/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    TheNavbar: typeof import('./src/components/TheNavbar.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WhatsappFloating: typeof import('./src/components/WhatsappFloating.vue')['default']
  }
}
