/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseModal: typeof import('./src/components/BaseModal.vue')['default']
    copy: typeof import('./src/components/TagRatings copy.vue')['default']
    DefaultLayout: typeof import('./src/layouts/DefaultLayout.vue')['default']
    HomeProducts: typeof import('./src/components/home/HomeProducts.vue')['default']
    HomeServices: typeof import('./src/components/home/HomeServices.vue')['default']
    ProductCard: typeof import('./src/components/products/ProductCard.vue')['default']
    ProductCardJoin: typeof import('./src/components/products/ProductCardJoin.vue')['default']
    ProductDetailFacility: typeof import('./src/components/products/ProductDetailFacility.vue')['default']
    ProductDetailGallery: typeof import('./src/components/products/ProductDetailGallery.vue')['default']
    ProductDetailReview: typeof import('./src/components/products/ProductDetailReview.vue')['default']
    ProductFacilities: typeof import('./src/components/products/ProductFacilities.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagRatings: typeof import('./src/components/TagRatings.vue')['default']
    TextRating: typeof import('./src/components/TextRating.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    TheNavbar: typeof import('./src/components/TheNavbar.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WhatsappFloating: typeof import('./src/components/WhatsappFloating.vue')['default']
  }
}
